language: go


os: linux
compiler: gcc
dist: trusty
sudo: required
cache: apt

# before_install:
  # - sudo apt-get install -y go

before_script:
  - echo before
  - go build -o citask citask.go

script:
  - ./citask --context t-test1 --description "tests" "sleep 5"
  - ./citask --context t-test2 --description "tests" "sleep 5 && echo done"
  - ./citask --context test3 --description "tests" "sleep 5 && echo done"
